WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
	[Authorize]
	public class HomeController : Controller
	{

		BookContext db = new BookContext();

		public ActionResult Index(int page = 1)
		{
			List<Book> books = db.Books.ToList();
			int pageSize = 3; // количество объектов на страницу
			IEnumerable<Book> booksPerPages = books.Skip((page - 1) * pageSize).Take(pageSize);
			PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = books.Count };
			IndexViewModel ivm = new IndexViewModel { PageInfo = pageInfo, Books = booksPerPages };
			ViewBag.Message = "Это вызов частичного представления из обычного";
			return View(ivm);
			//return View(db.Books);
		}



		[HttpGet]
		public ActionResult Buy(int id)
		{
			ViewBag.BookId = id;
			return View();
		}
		[HttpPost]
		public string Buy(Purchase purchase)
		{
			purchase.Date = DateTime.Now;
			// добавляем информацию о покупке в базу данных
			db.Purchases.Add(purchase);
			// сохраняем в бд все изменения
			db.SaveChanges();
			return "Спасибо," + purchase.Person + ", за покупку!";
		}



		[HttpGet]
		public ActionResult EditBook(int? id)
		{
			if (id == null)
			{
				return HttpNotFound();
			}
			Book book = db.Books.Find(id);
			if (book != null)
			{
				return View(book);
			}
			return HttpNotFound();
		}
		[HttpPost]
		public ActionResult EditBook(Book book)
		{
			db.Entry(book).State = EntityState.Modified;
			db.SaveChanges();
			return RedirectToAction("Index");
		}



		[HttpGet]
		public ActionResult Create()
		{
			return View();
		}
		[HttpPost]
		public ActionResult Create(Book book)
		{
			db.Books.Add(book);
			db.SaveChanges();

			return RedirectToAction("Index");
		}
		//[HttpPost]
		//public ActionResult Create(Book book)
		//{
		//	db.Entry(book).State = EntityState.Added;
		//	db.SaveChanges();

		//	return RedirectToAction("Index");
		//}



		[HttpGet]
		public ActionResult Delete(int id)
		{
			Book b = db.Books.Find(id);
			if (b == null)
			{
				return HttpNotFound();
			}
			return View(b);
		}
		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteConfirmed(int id)
		{
			Book b = db.Books.Find(id);
			if (b == null)
			{
				return HttpNotFound();
			}
			db.Books.Remove(b);
			db.SaveChanges();
			return RedirectToAction("Index");
		}



		[HttpGet]
		public ActionResult Detail(int id)
		{
			Book b = db.Books.Find(id);
			if (b == null)
			{
				return HttpNotFound();
			}
			return View(b);
		}
	}
}

WebApplication1/Controllers/MyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace WebApplication1.Controllers
{
	public class MyController : Controller
	{
		//public void Execute(RequestContext requestContext)
		//{
		//	string ip = requestContext.HttpContext.Request.UserHostAddress;
		//	var response = requestContext.HttpContext.Response;
		//	response.Write("<h2>Ваш IP-адрес: " + ip + "</h2>");
		//}

		public string Index()
		{
			string browser = HttpContext.Request.Browser.Browser;
			string user_agent = HttpContext.Request.UserAgent;
			string url = HttpContext.Request.RawUrl;
			string ip = HttpContext.Request.UserHostAddress;
			string referrer = HttpContext.Request.UrlReferrer == null ? "" : HttpContext.Request.UrlReferrer.AbsoluteUri;
			return "<p>Browser: " + browser + "</p><p>User-Agent: " + user_agent + "</p><p>Url запроса: " + url +
					"</p><p>Реферер: " + referrer + "</p><p>IP-адрес: " + ip + "</p>";
		}

		public string Square(int a = 10, int h = 3)
		{
			double s = a * h / 2.0;
			return "<h2>Площадь треугольника с основанием " + a +
							" и высотой " + h + " равна " + s + "</h2>";
		}

		public RedirectResult Redirect()
		{
			return Redirect("/Home/Index");
		}

		public ActionResult Test()
		{
			//return new HttpStatusCodeResult(404);
			return new HttpUnauthorizedResult();
			//return HttpNotFound();
			//return Content("<h2>aaaaaaaaaaaaaa<h2>");
		}

		public FileResult GetFile()
		{
			// Путь к файлу
			string file_path = Server.MapPath("~/Files/PDFIcon.pdf");
			// Тип файла - content-type
			string file_type = "application/pdf";
			// Имя файла - необязательно
			string file_name = "PDFIcon.pdf";
			return File(file_path, file_type, file_name);
		}

		public string ContextData()
		{
			HttpContext.Response.Write("<h1>Hello World</h1>");

			string user_agent = HttpContext.Request.UserAgent;
			string url = HttpContext.Request.RawUrl;
			string ip = HttpContext.Request.UserHostAddress;
			string referrer = HttpContext.Request.UrlReferrer == null ? "" : HttpContext.Request.UrlReferrer.AbsoluteUri;
			return "<p>User-Agent: " + user_agent + "</p><p>Url запроса: " + url +
					"</p><p>Реферер: " + referrer + "</p><p>IP-адрес: " + ip + "</p>";
		}

		public ActionResult Partial()
		{
			ViewBag.Message = "Это частичное представление.";
			return PartialView();
		}
	}
}

WebApplication1/Views/Home/Buy.cshtml
@{
    ViewBag.Title = "Покупка";
}

<div>
	<h3>Форма оформления покупки</h3>
	<form method="post" action="">
		<input type="hidden" value="@ViewBag.BookId" name="BookId" />
		<table>
			<tr>
				<td><p>Введите свое имя </p></td>
				<td><input type="text" name="Person" /> </td>
			</tr>
			<tr>
				<td><p>Введите адрес :</p></td>
				<td>
					<input type="text" name="Address" />
				</td>
			</tr>
			<tr><td><input type="submit" value="Отправить" /> </td><td></td></tr>
		</table>
	</form>
</div>

WebApplication1/Views/Home/Create.cshtml
@model WebApplication1.Models.Book

@{
	ViewBag.Title = "Новая книга";
}

<h2>Новая книга</h2>

@using (Html.BeginForm())
{
	@Html.LabelFor(model => model.Name, "Название книги")
	<br />
	@Html.EditorFor(model => model.Name)
	<br /><br />
	@Html.LabelFor(model => model.Author, "Автор")
	<br />
	@Html.EditorFor(model => model.Author)
	<br /><br />
	@Html.LabelFor(model => model.Price, "Цена")
	<br />
	@Html.EditorFor(model => model.Price)
	<br /><br />
	<input type="submit" value="Добавить" />
}

WebApplication1/Views/Home/Delete.cshtml
@model WebApplication1.Models.Book

@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Удаление книги</h2>
<dl>
	<dt>Название</dt>
	<dd>
		@Html.DisplayFor(model => model.Name)
	</dd>

	<dt>Автор</dt>
	<dd>
		@Html.DisplayFor(model => model.Author)
	</dd>

	<dt>Цена</dt>
	<dd>
		@Html.DisplayFor(model => model.Price)
	</dd>
</dl>

@using (Html.BeginForm())
{
	<input type="submit" value="Удалить"   />
}

WebApplication1/Views/Home/Detail.cshtml
@using WebApplication1.Models
@model Book

<h2>Книга № @Model.Id</h2>
@Html.DisplayForModel()

WebApplication1/Views/Home/EditBook.cshtml
@model WebApplication1.Models.Book

@{
	ViewBag.Title = "Редактировать книгу";
}

<h2>Книга № @Model.Id</h2>
@using (Html.BeginForm("EditBook", "Home", FormMethod.Post))
{
	<fieldset>
		@Html.HiddenFor(m => m.Id)
		<p>
			@Html.LabelFor(m => m.Name, "Название книги")
			<br />
			@Html.EditorFor(m => m.Name)
		</p>
		<p>
			@Html.LabelFor(m => m.Author, "Автор")
			<br />
			@Html.EditorFor(m => m.Author)

		</p>
		<p>
			@Html.LabelFor(m => m.Price, "Цена")
			<br />
			@Html.EditorFor(m => m.Price)
		</p>
		<p><input type="submit" value="Отправить" /></p>
	</fieldset>
}

WebApplication1/Views/Home/Index.cshtml
@model WebApplication1.Models.IndexViewModel
@using WebApplication1.Helpers

@{
	ViewBag.Title = "Книжный магазин";
}

<div>
	<h3>Распродажа книг</h3>
	@Html.ActionLink("Добавить книгу", "Create")
	<table>
		<tr>
			<td><p>Название книги</p></td>
			<td><p>Автор</p></td>
			<td><p>Цена</p></td>
			<td></td>
		</tr>
		@foreach (var b in Model.Books)
		{
			<tr>
				<td><p>@b.Name</p></td>
				<td><p>@b.Author</p></td>
				<td><p>@b.Price</p></td>
				<td><p><a href="/Home/Buy/@b.Id">Купить</a></p></td>
			</tr>
		}
	</table>
	@Html.PageLinks(Model.PageInfo, x => Url.Action("Index", new { page = x }))

	@*@Html.Action("Partial", "My")*@
	@Html.Partial("~/Views/My/Partial.cshtml")
</div>